export const ASSIGNMENT_REVIEW_MAP_DEFAULT_CENTER_LAT = 31.5;
export const ASSIGNMENT_REVIEW_MAP_DEFAULT_CENTER_LON = 34.8;
export const ASSIGNMENT_REVIEW_MAP_DEFAULT_ZOOM = 8;
export const ASSIGNMENT_REVIEW_MAP_FIT_PADDING_PX = 40;
export const ASSIGNMENT_REVIEW_MAP_UAV_ICON_WIDTH_PX = 36;
export const ASSIGNMENT_REVIEW_MAP_UAV_ICON_HEIGHT_PX = 40;
export const ASSIGNMENT_REVIEW_MAP_MISSION_ICON_WIDTH_PX = 36;
export const ASSIGNMENT_REVIEW_MAP_MISSION_ICON_HEIGHT_PX = 40;
export const ASSIGNMENT_REVIEW_MAP_LINE_WEIGHT = 3;
export const ASSIGNMENT_REVIEW_MAP_LINE_OPACITY = 0.85;

export const ASSIGNMENT_REVIEW_MAP_UAV_COLOR_UNASSIGNED = '#9e9e9e';
export const ASSIGNMENT_REVIEW_MAP_UAV_COLOR_ASSIGNED = '#1976d2';
export const ASSIGNMENT_REVIEW_MAP_MISSION_FILL = '#c62828';
export const ASSIGNMENT_REVIEW_MAP_MISSION_STROKE = '#b71c1c';

export const ASSIGNMENT_REVIEW_MAP_LINE_HUES: readonly number[] = [210, 120, 45, 280, 160, 330];

export const ASSIGNMENT_REVIEW_MAP_OS_TILE_TEMPLATE =
  'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';

export const ASSIGNMENT_REVIEW_MAP_TILE_ATTRIBUTION =
  '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>';
