import { Component, output, input, OnInit, signal } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UAVType, Priority } from '../../common/enums';
import { ClientConstants } from '../../common';

const { LocationValidation } = ClientConstants.ValidationConstants;
const { EMPTY_STRING, DEFAULT_NUMBER } = ClientConstants.FormDefaults;

@Component({
  selector: 'app-mission-component',
  standalone: false,
  templateUrl: './mission-component.component.html',
  styleUrl: './mission-component.component.scss',
})
export class MissionComponentComponent implements OnInit {
  public readonly autoGeneratedId = input.required<number>();
  public readonly uavTypes: UAVType[] = Object.values(UAVType);
  public readonly priority: Priority[] = Object.values(Priority);
  public readonly remove = output<void>();

  public readonly isLocationExpanded = signal<boolean>(false);
  public readonly isTimeWindowExpanded = signal<boolean>(false);

  public readonly missionForm: FormGroup = new FormGroup({
    missionId: new FormControl(EMPTY_STRING, [Validators.required]),
    requiredUAVType: new FormControl(EMPTY_STRING, [Validators.required]),
    priority: new FormControl(EMPTY_STRING, [Validators.required]),
    location: this.createLocationFormGroup(),
    timeWindow: this.createTimeWindowFormGroup(),
  });

  public ngOnInit(): void {
    this.missionForm.patchValue({
      missionId: `MISSION-${this.autoGeneratedId()}`,
    });
  }

  public onRemove(): void {
    this.remove.emit();
  }

  public toggleLocation(): void {
    this.isLocationExpanded.update((value) => !value);
  }

  public toggleTimeWindow(): void {
    this.isTimeWindowExpanded.update((value) => !value);
  }

  public get isFormValid(): boolean {
    return this.missionForm.valid;
  }

  private createLocationFormGroup(): FormGroup {
    return new FormGroup({
      latitude: new FormControl(DEFAULT_NUMBER, [
        Validators.required,
        Validators.min(LocationValidation.LATITUDE_MIN),
        Validators.max(LocationValidation.LATITUDE_MAX),
      ]),
      longitude: new FormControl(DEFAULT_NUMBER, [
        Validators.required,
        Validators.min(LocationValidation.LONGITUDE_MIN),
        Validators.max(LocationValidation.LONGITUDE_MAX),
      ]),
      altitude: new FormControl(DEFAULT_NUMBER, [Validators.required]),
    });
  }

  private createTimeWindowFormGroup(): FormGroup {
    return new FormGroup({
      start: new FormControl(null, [Validators.required]),
      end: new FormControl(null, [Validators.required]),
    });
  }
}
