import { Component, output, input, OnInit, signal } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { UAVType, Priority } from '../../common/enums';
import { ClientConstants } from '../../common';
import { EnumUtil } from '../../common/utils';
import { timeWindowValidator } from '../../common/validators';
import type { Mission } from '../../models';

const { LocationValidation } = ClientConstants.ValidationConstants;
const { EMPTY_STRING } = ClientConstants.FormDefaults;

@Component({
  selector: 'app-mission-component',
  standalone: false,
  templateUrl: './mission-component.component.html',
  styleUrl: './mission-component.component.scss',
})
export class MissionComponentComponent implements OnInit {
  public readonly autoGeneratedId = input.required<number>();
  public readonly mission = input<Mission | null>(null);
  public readonly uavTypes: UAVType[] = Object.values(UAVType);
  public readonly priority: Priority[] = Object.values(Priority);
  public readonly remove = output<void>();
  public readonly formChange = output<void>();
  public readonly EnumUtil = EnumUtil;

  public readonly isLocationExpanded = signal<boolean>(false);
  public readonly isTimeWindowExpanded = signal<boolean>(false);

  public readonly missionForm: FormGroup = new FormGroup({
    missionId: new FormControl(EMPTY_STRING, [Validators.required]),
    title: new FormControl(EMPTY_STRING, [Validators.required]),
    requiredUAVType: new FormControl(EMPTY_STRING, [Validators.required]),
    priority: new FormControl(EMPTY_STRING, [Validators.required]),
    location: this.createLocationFormGroup(),
    timeWindow: this.createTimeWindowFormGroup(),
  });

  public ngOnInit(): void {
    const existingMission = this.mission();
    if (existingMission) {
      this.missionForm.patchValue({
        missionId: existingMission.id,
        title: existingMission.title,
        requiredUAVType: existingMission.requiredUAVType,
        priority: existingMission.priority,
        location: existingMission.location,
        timeWindow: existingMission.timeWindow,
      });
    } else {
      this.missionForm.patchValue({
        missionId: crypto.randomUUID(),
      });
    }

    this.missionForm.valueChanges.subscribe(() => {
      this.formChange.emit();
    });
  }

  public onRemove(): void {
    this.remove.emit();
  }

  public toggleLocation(): void {
    this.isLocationExpanded.update((value) => !value);
  }

  public toggleTimeWindow(): void {
    this.isTimeWindowExpanded.update((value) => !value);
  }

  public get isFormValid(): boolean {
    return this.missionForm.valid;
  }

  public onCardBlur(): void {
    this.missionForm.markAllAsTouched();
  }

  private createLocationFormGroup(): FormGroup {
    return new FormGroup({
      latitude: new FormControl(null, [
        Validators.required,
        Validators.min(LocationValidation.LATITUDE_MIN),
        Validators.max(LocationValidation.LATITUDE_MAX),
      ]),
      longitude: new FormControl(null, [
        Validators.required,
        Validators.min(LocationValidation.LONGITUDE_MIN),
        Validators.max(LocationValidation.LONGITUDE_MAX),
      ]),
      altitude: new FormControl(null, [Validators.required]),
    });
  }

  private createTimeWindowFormGroup(): FormGroup {
    return new FormGroup(
      {
        start: new FormControl(null, [Validators.required]),
        end: new FormControl(null, [Validators.required]),
      },
      { validators: timeWindowValidator() }
    );
  }
}
