export enum TelemetryField {
  DragCoefficient = 'DragCoefficient',
  LiftCoefficient = 'LiftCoefficient',
  ThrottlePercent = 'ThrottlePercent',
  CruiseAltitude = 'CruiseAltitude',
  Latitude = 'Latitude',
  LandingGearStatus = 'LandingGearStatus',
  Longitude = 'Longitude',
  Altitude = 'Altitude',
  CurrentSpeedKmph = 'CurrentSpeedKmph',
  YawDeg = 'YawDeg',
  PitchDeg = 'PitchDeg',
  RollDeg = 'RollDeg',
  ThrustAfterInfluence = 'ThrustAfterInfluence',
  FuelAmount = 'FuelAmount',
  DataStorageUsedGB = 'DataStorageUsedGB',
  FlightTimeSec = 'FlightTimeSec',
  SignalStrength = 'SignalStrength',
  Rpm = 'Rpm',
  EngineDegrees = 'EngineDegrees',
  NearestSleeveId = 'NearestSleeveId',
  TailId = 'TailId',
  UAVTypeValue = 'UAVTypeValue',
}
